api:
  build: api/
  environment:
    - PGHOST=postgresdb.dev
    - PGPASSWORD=password1
    - PGUSER=sacsos
  ports:
    - "3001:3000"
  # volumes:
  #   - ../ohana-api:/home/sacsos/api
  links:
    - "pg:postgresdb.dev"
pg:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=password1
    - POSTGRES_USER=sacsos
