version: '2'
services:
  api:
    build: api/
    environment:
      - VIRTUAL_HOST=ohana-api.dev
      - PGHOST=postgresdb.dev
      - PGPASSWORD=password1
      - PGUSER=sacsos
    ports:
    - "3001:3001"
    volumes:
      - ./api/files/application.yml:/home/sacsos/api/config/application.yml
    links:
      - "pg:postgresdb.dev"
  web:
    build: web/
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=web.local
    links:
      - "api:api.lvh.me"
    volumes:
      - ./web/files/application.yml:/home/sacsos/api/config/application.yml
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password1
      - POSTGRES_USER=sacsos
    # volumes:
    #   - /home/jeff/projects/ohana-data/backups:/backups
